name: CompileAndRunProgram

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: compileit
      run: Project2/make
    - name: runit
      run: ./Project2/prog ./datasets/camera_specs/2013_camera_specs ./datasets/sigmod_large_labelled_dataset.csv Project2/common-english-words.txt
