name: Ex

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: compileit
      run: make
    - name: runit
      run: ./prog ./datasets/camera_specs/2013_camera_specs ./datasets/sigmod_large_labelled_dataset.csv
